name: android-apk (debug)

on:
  push:
    branches: [ "dguo" ]
  pull_request:
    branches: [ "dguo" ]

permissions:
  contents: read

env:
  JAVA_VERSION: "17"
  ANDROID_API_LEVEL: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"

jobs:
  build-apk-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-${{ env.ANDROID_API_LEVEL }}
            build-tools;${{ env.ANDROID_BUILD_TOOLS }}

      # 如果你的 Android 工程在 project/ 目录，请把 working-directory 改为 project
      - name: Grant execute permission for gradlew
        working-directory: project
        run: chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: project
        run: ./gradlew --no-daemon clean assembleDebug

      # 扫描所有模块的 debug APK，复制到 artifacts/ 并语义化命名
      - name: Collect & rename APKs (flat)
        id: collect
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p artifacts
          shopt -s globstar nullglob
          count=0
          shortsha="${GITHUB_SHA::7}"
          # 典型路径：<module>/build/outputs/apk/debug/*.apk
          for apk in project/**/build/outputs/apk/debug/*.apk; do
            # 取模块名（build 之前的目录名）
            module="$(echo "$apk" | sed -E 's#.*/([^/]+)/build/outputs/apk/debug/[^/]+$#\1#')"
            out="artifacts/${module}-debug-${GITHUB_RUN_NUMBER}-${shortsha}.apk"
            cp -f "$apk" "$out"
            echo "collected: $out"
            count=$((count+1))
          done
          if [ "$count" -eq 0 ]; then
            echo "没有找到 Debug APK，请确认模块路径与构建任务。" >&2
            exit 1
          fi
          echo "apk_count=$count" >> "$GITHUB_OUTPUT"

      - name: Upload Debug APK artifact (flat)
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug-${{ github.run_number }}
          path: artifacts/*.apk
          if-no-files-found: error
          retention-days: 14
