name: android-apk (debug)

on:
  push:
    branches: [ "dguo" ]
  pull_request:
    branches: [ "dguo" ]

permissions:
  contents: read

env:
  JAVA_VERSION: "17"
  ANDROID_API_LEVEL: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"

jobs:
  build-apk-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v3

      - uses: android-actions/setup-android@v3
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          build-tools: ${{ env.ANDROID_BUILD_TOOLS }}

      - name: Grant execute permission
        working-directory: project
        run: chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: project
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-${{ github.run_number }}-${{ github.sha }}
          path: project/**/build/outputs/apk/debug/*.apk
          if-no-files-found: error
