name: test-and-deploy

on:
  push:
    branches: [ "dguo", "main", "master" ]
  pull_request:
    branches: [ "dguo", "main", "master" ]

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "18.x"
  GO_VERSION: "1.22.x"
  JAVA_VERSION: "17"

jobs:
  # --------------------------------------------------
  # 预处理：探测项目类型并输出到 needs.prepare.outputs.*
  # --------------------------------------------------
  prepare:
    runs-on: ubuntu-latest
    outputs:
      has_node:   ${{ steps.detect.outputs.has_node }}
      has_go:     ${{ steps.detect.outputs.has_go }}
      has_gradle: ${{ steps.detect.outputs.has_gradle }}
      has_docker: ${{ steps.detect.outputs.has_docker }}
      has_jshint_dir: ${{ steps.detect.outputs.has_jshint_dir }}
    steps:
      - uses: actions/checkout@v4

      - id: detect
        shell: bash
        run: |
          echo "has_node=$([ -f package.json ] && echo true || echo false)" >> "$GITHUB_OUTPUT"
          echo "has_go=$([ -f go.mod ] && echo true || echo false)" >> "$GITHUB_OUTPUT"
          echo "has_gradle=$([ -f gradlew ] && echo true || echo false)" >> "$GITHUB_OUTPUT"
          echo "has_docker=$([ -f Dockerfile ] && echo true || echo false)" >> "$GITHUB_OUTPUT"
          echo "has_jshint_dir=$([ -d .github/workflows/jshint ] && echo true || echo false)" >> "$GITHUB_OUTPUT"

  # ---------------------------
  # Node.js: npm install / test
  # ---------------------------
  test-node:
    name: Node tests
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.has_node == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Test (if script exists)
        run: |
          if npm run | grep -qE '(^|\s)test(\s|:)'; then
            npm test --silent
          else
            echo "No npm test script, skipping"
          fi

      - name: Run local jshint action (if present)
        if: ${{ needs.prepare.outputs.has_jshint_dir == 'true' }}
        uses: ./.github/workflows/jshint

  # ---------------------------
  # Go: go test ./...
  # ---------------------------
  test-go:
    name: Go tests
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.has_go == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Test
        run: go test ./... -v

  # ---------------------------
  # Android/Gradle build
  # ---------------------------
  build-android:
    name: Android build
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.has_gradle == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build (assembleDebug)
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK/AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
          if-no-files-found: ignore

  # ---------------------------
  # Deploy:
  #   1) Dockerfile -> GHCR
  #   2) else Node -> GitHub Pages (dist or build)
  # ---------------------------
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [prepare, test-node, test-go, build-android]
    # 仅在 dguo 分支或打 tag 时部署
    if: ${{ github.ref == 'refs/heads/dguo' || startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4

      # ---- 路径 1：Docker 发布到 GHCR（若存在 Dockerfile）----
      - name: Log in to GHCR
        if: ${{ needs.prepare.outputs.has_docker == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        if: ${{ needs.prepare.outputs.has_docker == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]'):${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]'):latest

      # ---- 路径 2：Node 静态站点部署到 Pages（当无 Dockerfile 且为 Node 项目）----
      - name: Setup Node (for build)
        if: ${{ needs.prepare.outputs.has_docker != 'true' && needs.prepare.outputs.has_node == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps (for build)
        if: ${{ needs.prepare.outputs.has_docker != 'true' && needs.prepare.outputs.has_node == 'true' }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build site (if script exists)
        if: ${{ needs.prepare.outputs.has_docker != 'true' && needs.prepare.outputs.has_node == 'true' }}
        run: |
          if npm run | grep -qE '(^|\s)build(\s|:)'; then
            npm run build
          else
            echo "No build script; skipping"
          fi

      - name: Setup Pages
        if: ${{ needs.prepare.outputs.has_docker != 'true' && needs.prepare.outputs.has_node == 'true' }}
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact (dist or build)
        if: ${{ needs.prepare.outputs.has_docker != 'true' && needs.prepare.outputs.has_node == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            dist
            build
          if-no-files-found: ignore

      - name: Deploy to GitHub Pages
        if: ${{ needs.prepare.outputs.has_docker != 'true' && needs.prepare.outputs.has_node == 'true' }}
        id: deployment
        uses: actions/deploy-pages@v4
